package lytro {
	import flash.display.*
	
	/**
	 * A class the holds the resources found in a .lfp light field picture. 
	 * 
	 * Typically generated by LFPDecoder.
	 */
	public class LightFieldPicture {
		public var
			images:Vector.<BitmapData>,
			depths:Vector.<Number>,
			metadata:*
			
		public function LightFieldPicture(){
			images = new <BitmapData>[]
			depths = new <Number>[]
			metadata = {}
		}
	}
}